### ISSUE TITLE
Error -> WatchDog Database Exception: Column length too big for column 'queryString'

### ISSUE THREAD

**Issue by SantiagoDeLaTorre** [IzyPro/WatchDog#121]
Hello,

I have configured my application and when I try to start my webapp for the first time, I get the following error:

'WatchDog Database Exception: Column length too big for column 'queryString' (max = 16383); use BLOB or TEXT instead Ensure you have passed the right Database Driver Option or a proper connection string at .AddWatchDogServices() as well as all required parameters for the database connection string'

I'm using:
- Asp.Net Core 7
- Mysql 8.0.32

The connection string I give you is correct:
"server=localhost;port=3306;user=root;password=supersecretpass;database=StoreApp"

And this using the correct driver:
opt.DbDriverOption = WatchDog.src.Enums.WatchDogDbDriverEnum.MySql;

Thanks

**Comment by IzyPro** [comment]
Hi @SantiagoDeLaTorre 

Did you say you experience this error on start of your application? Or when an endpoint is called.

Also, what version of WatchDog was used to create the first migration to the database?

**Comment by SantiagoDeLaTorre** [comment]
The version is: 1.4.7

The error occurs when starting the webapp.

![image](https://user-images.githubusercontent.com/2223013/233736934-6d420d6e-c55f-408f-9ef8-93f6efcd0822.png)

**Comment by IzyPro** [comment]
Hi @SantiagoDeLaTorre 

It is really strange that you are getting this error, especially on web app startup because it shouldn't even be logging at that point.
Anyways, you could try running a query in your DB to change the column type for the `queryString` parameter to TEXT and let's see if that fixes it for you.
The query will look something like this:

ALTER TABLE WatchDog_WatchLogs
MODIFY queryStringTEXT(65535);
