### ISSUE TITLE
Everything become undefined when you refresh watchdog ui

### ISSUE THREAD

**Issue by tylndemirci** [IzyPro/WatchDog#52]
When I refresh the page, everything becomes undefined, but you can see the information when you look at the network

![image](https://user-images.githubusercontent.com/60180444/183136584-85bace93-2e0e-4afe-adf4-da8008127c9e.png)

**Comment by tylndemirci** [comment]
Just figured out the initials must be uppercase letter, it solves the problem.
![image](https://user-images.githubusercontent.com/60180444/183139717-1685d9d9-0af4-4faf-98e1-14fbc7c57811.png)

**Comment by IzyPro** [comment]
Hi @tylndemirci 
It's great to hear that you've solved the problem.
However, if you could give a detailed report on how you encountered this issue and the steps you took it would go a long way in helping others solve this and also help us prevent future issues.
Other important details will include the project type, framework version, database used for logs etc.

**Comment by Suhut** [comment]
> Just figured out the initials must be uppercase letter, it solves the problem. ![image](https://user-images.githubusercontent.com/60180444/183139717-1685d9d9-0af4-4faf-98e1-14fbc7c57811.png) ![image](https://user-images.githubusercontent.com/60180444/183139948-edb35223-af59-460e-bef8-588f952a520e.png)

the error still appear in version 1.3.2

**Comment by IzyPro** [comment]
Hi @Suhut 
Kindly provide steps to reproduce as well as all necessary information using the template below:

**Description**

A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Details** (please complete the following information):

Project Type: [e.g. API, MVC]
Framework Version [e.g. .NET Core 3.1, .NET 6]
WatchDog Version [e.g. 1.3.0, 1.2.1]
Database [e.g Default, MySQL]

**Additional context**
Add any other context about the problem here.

**Comment by IzyPro** [comment]
If you experience a similar issue, refer to: https://github.com/IzyPro/WatchDog/issues/66
